# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIp8iye7LFBuCO0ysx3E9MzTrat2elKp

## Gradio Pets
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -Uqq fastai
# %pip install -Uqq fastai gradio

from fastai.vision.all import *
import gradio as gr

def is_cats(x): return x[0].isupper()

img = PILImage.create('Labardor.jpg')

img.thumbnail((512,512))
img

learn = load_learner('model.pkl')

def predict(img):
    img = PILImage.create(img)
    img.thumbnail((512,512))
    pred,pred_idx,probs = learn.predict(img)
    if pred == 'cats':
        return f"This is a cat with probability {probs[pred_idx]:.04f}"
    else:
        return f"This is a dog with probability {probs[pred_idx]:.04f}"
examples=['Labardor.jpg']

gr.Interface(fn=predict, inputs="image", outputs="text", examples=examples).launch()